apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alpha-engine.fullname" . }}-config
  labels:
    {{- include "alpha-engine.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}