{
 "title": "Alpha Engine Platform",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  kube_pod_status_phase{\n    namespace=\"$namespace\",\n    phase=\"Running\",\n    pod=~\"alpha-engine.*\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{job=~\"$namespace.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=\"$namespace\",\n      container=\"alpha-engine\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    namespace=\"$namespace\",\n    container=\"alpha-engine\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Exchanges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alpha_engine_configured_exchanges{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Configured Pairs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alpha_engine_configured_pairs{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Exchanges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alpha_engine_connected_exchanges{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(alpha_engine_database_connected{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=\"$namespace\",\n      container=\"alpha-engine\"\n    }[5m]\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{\n    namespace=\"$namespace\",\n    container=\"alpha-engine\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"$namespace\", app=\"alpha-engine\"}"
    }
   ]
  }
 ]
}