kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: "AlphaEngine2026!"
    additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        isDefault: false
        editable: true