apiVersion: v2
name: postgres-exporter
description: PostgreSQL exporter for Alpha Engine platform
type: application
version: 0.1.0
appVersion: "0.17.1"

dependencies:
  - name: prometheus-postgres-exporter
    version: 7.0.0
    repository: https://prometheus-community.github.io/helm-charts